#!/usr/bin/env bash
# Create homepage DZI pyramids for tile server.
#
# JXL baseline pyramids:
#   Levels 0-13: static JPEGs copied from jpeg90 (thumbnail pyramid)
#   Level 14 (L2): empty — server generates via downsampling
#   Level 15 (L1): empty — server generates via downsampling
#   Level 16 (L0): 1024px JXL tiles from DICOM source
#
# ORIGAMI pyramids:
#   Generated by origami encode --pyramid

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$SCRIPT_DIR/.."
BIN="${BIN:-$ROOT/server/target2/release/origami}"
SRC_PYRAMID="$ROOT/data/dzi/jpeg90"
DICOM_L0="$ROOT/data/dzi/dicom_extract_1024/baseline_pyramid_files/16"
DZI_DIR="$ROOT/data/dzi"

# Copy static thumbnail levels (0-13) from jpeg90
copy_thumbnail_levels() {
    local out=$1
    mkdir -p "$out/baseline_pyramid_files"
    for lvl in $(seq 0 13); do
        cp -R "$SRC_PYRAMID/baseline_pyramid_files/$lvl" "$out/baseline_pyramid_files/$lvl"
    done
    # Empty L2 and L1 dirs
    mkdir -p "$out/baseline_pyramid_files/14"
    mkdir -p "$out/baseline_pyramid_files/15"
    mkdir -p "$out/baseline_pyramid_files/16"
    # DZI manifest (256px tile size)
    cp "$SRC_PYRAMID/baseline_pyramid.dzi" "$out/baseline_pyramid.dzi"
}

# ─── JXL Lossless ───
create_jxl_lossless() {
    local out="$DZI_DIR/jxl_lossless"
    if [ -f "$out/summary.json" ]; then
        echo "SKIP jxl_lossless (exists)"
        return
    fi
    echo "=== JXL Lossless ==="
    copy_thumbnail_levels "$out"

    local count=$(ls "$DICOM_L0"/*.jpg 2>/dev/null | wc -l | tr -d ' ')
    local i=0
    for f in "$DICOM_L0"/*.jpg; do
        local base=$(basename "$f" .jpg)
        cjxl "$f" "$out/baseline_pyramid_files/16/${base}.jxl" -d 0 2>/dev/null
        i=$((i + 1))
        if [ $((i % 500)) -eq 0 ]; then echo "  $i / $count"; fi
    done
    cat > "$out/summary.json" << EOFS
{
    "label": "JXL Lossless",
    "mode": "jxl-baseline",
    "quality": "lossless",
    "tiles": $i,
    "pipeline_version": 2
}
EOFS
    echo "  Done: $i tiles"
}

# ─── JXL Q80/Q70 ───
create_jxl_quality() {
    local quality=$1
    local out="$DZI_DIR/jxl_${quality}"
    if [ -f "$out/summary.json" ]; then
        echo "SKIP jxl_${quality} (exists)"
        return
    fi
    echo "=== JXL Q${quality} ==="
    copy_thumbnail_levels "$out"

    local count=$(ls "$DICOM_L0"/*.jpg 2>/dev/null | wc -l | tr -d ' ')
    local i=0
    for f in "$DICOM_L0"/*.jpg; do
        local base=$(basename "$f" .jpg)
        cjxl "$f" "$out/baseline_pyramid_files/16/${base}.jxl" -q "$quality" --lossless_jpeg=0 2>/dev/null
        i=$((i + 1))
        if [ $((i % 500)) -eq 0 ]; then echo "  $i / $count"; fi
    done
    cat > "$out/summary.json" << EOFS
{
    "label": "JXL Q${quality}",
    "mode": "jxl-baseline",
    "quality": $quality,
    "tiles": $i,
    "pipeline_version": 2
}
EOFS
    echo "  Done: $i tiles"
}

# ─── ORIGAMI pyramids ───
create_origami() {
    local name=$1 seedq=$2 l0q=$3; shift 3
    local extra="$@"
    local out="$DZI_DIR/$name"
    if [ -f "$out/summary.json" ]; then
        echo "SKIP $name (exists)"
        return
    fi
    echo "=== $name (SQ${seedq} L0Q${l0q}) ==="
    RUST_LOG=info "$BIN" encode \
        --pyramid "$SRC_PYRAMID" \
        --out "$out" \
        --seedq "$seedq" --l0q "$l0q" --seed-size 256 \
        --subsamp 444 --upsample-filter lanczos3 \
        --pack $extra 2>&1 | tail -3
}

# ─── Generate all ───
create_jxl_lossless
create_jxl_quality 80
create_jxl_quality 70

create_origami origami_90_40 90 40 --denoise --denoise-weight 0.0
create_origami origami_90_70 90 70
create_origami origami_95_80 95 80

echo ""
echo "=== All homepage pyramids ==="
ls -d "$DZI_DIR"/origami_* "$DZI_DIR"/jxl_* 2>/dev/null
